Экспорт расписания
Namxobick/unn-mobile pull request #65
Opened 2023-11-15 18:16 UTC by Namxobick

- [x] Android
- [ ] IOS

2023-11-15 18:20 UTC, Namxobick commented
Предоставление обработчика разрешений не отображается на iOS

2023-11-17 09:38 UTC, Namxobick commented
На данный момент необходимо полное разрешение. Возможно позже смогу сделать так, чтобы требовалось разрешение только на запись

2023-11-17 17:37 UTC, KriseevM commented
Конфликты решай))

2023-11-18 22:41 UTC, KriseevM requested changes

2023-11-18 22:41 UTC, KriseevM commented on lib/core/services/implementations/export_schedule_service_impl.dart
> +  final String _lng = '1';
```suggestion
  final String _lng = 'lng';
```

2023-11-18 22:41 UTC, KriseevM commented on lib/core/services/interfaces/export_schedule_service.dart
>  abstract interface class ExportScheduleService{
```suggestion
abstract interface class ExportScheduleService {
```

2023-11-18 22:41 UTC, KriseevM commented on lib/core/services/interfaces/export_schedule_service.dart
> +  /// Запршивает  разрешение на использование календаря
```suggestion
  /// Запрашивает  разрешение на использование календаря
```

2023-11-18 22:41 UTC, KriseevM commented on lib/core/services/interfaces/export_schedule_service.dart
> +  /// Возращает [RequestCalendarPermissionResult]:
```suggestion
  /// Возвращает [RequestCalendarPermissionResult]:
```

2023-11-18 22:41 UTC, KriseevM commented on lib/core/services/interfaces/export_schedule_service.dart
> +  /// - [RequestCalendarPermissionResult.rejected] - если пользователь не предоставил разрешение в сплывающем окне
```suggestion
  /// - [RequestCalendarPermissionResult.rejected] - если пользователь не предоставил разрешение в всплывающем окне
```

2023-11-18 22:41 UTC, KriseevM commented on lib/core/services/interfaces/export_schedule_service.dart
> +  /// - [RequestCalendarPermissionResult.permanentlyDenied] - если пользователь ранее не разрешил редактирование календаря
```suggestion
  /// - [RequestCalendarPermissionResult.permanentlyDenied] - если пользователь ранее запретил редактирование календаря
```

2023-11-18 22:41 UTC, KriseevM commented on lib/core/services/interfaces/export_schedule_service.dart
> +  /// Открывает настроки приложения
```suggestion
  /// Открывает настройки приложения
```

2023-11-18 22:44 UTC, KriseevM approved these changes

2023-11-18 22:45 UTC, merged